name: Node.js Package

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: install package dependencies
        run: yarn

      - name: build package
        run: yarn build

      - name: publish package
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

